import { motion } from "framer-motion";
import { useState } from "react";
import { BookOpen, ExternalLink } from "lucide-react";
import { SectionLabel } from "./SectionLabel";
import { DetailModal, MetaRow, Section } from "./DetailModal";
import { Fireflies } from "./Fireflies";

type ResearchItem = {
  id: string;
  title: string;
  outcome: string;
  year: string;
  summary: string;
  points: string[];
  presentations?: string[];
  doi?: string;
};

const researchItems: ResearchItem[] = [
  {
    id: "r1",
    title:
      "Operationalizing WHO Ethical Principles for Healthcare AI: A Lifecycle-Aligned Governance-by-Design Framework",
    outcome: "Published in AI in Medicine",
    year: "2026",
    doi: "https://doi.org/10.3390/aimed1020016",
    summary:
      "A governance-by-design framework that translates WHO ethical AI principles into practical lifecycle processes for healthcare AI deployment.",
    points: [
      "Developed lifecycle-aligned governance processes across design, validation, deployment, monitoring, and retirement.",
      "Identified gaps in bias assessment, robustness evaluation, model validation, and post-deployment monitoring.",
      "Designed practical governance mechanisms supporting responsible deployment of clinical AI systems.",
    ],
    presentations: [
      "Presented at Mayo AI Research Summit 2026",
      "Presented at IEEE Innovators Summit 2025",
    ],
  },
  {
    id: "r2",
    title:
      "Melanoma Detection and Calibration: Discrimination–Calibration Tradeoffs in Deep Learning",
    outcome: "Research in progress",
    year: "2026",
    summary:
      "A trustworthy medical AI study examining discrimination-calibration tradeoffs in deep learning-based melanoma classification.",
    points: [
      "Trained ResNet50 models on the ISIC 2019 dataset using stratified five-fold cross-validation.",
      "Evaluated calibration techniques including temperature scaling and logit prior correction.",
      "Performed external validation on HAM10000 to assess robustness under dataset shift.",
    ],
  },
  {
    id: "r3",
    title:
      "Evaluating the Fairness of Counterfactual Explanations Across Demographic Groups",
    outcome: "Research in progress",
    year: "2026",
    summary:
      "A fairness and explainable AI study evaluating whether machine learning models provide equitable recourse recommendations across demographic groups.",
    points: [
      "Evaluated counterfactual explanations generated by Logistic Regression, Random Forest, and XGBoost models.",
      "Measured disparities in recourse effort and success rates across sex, age, and race groups.",
      "Explored evaluation frameworks for trustworthy and equitable AI systems.",
    ],
  },
  {
    id: "r4",
    title:
      "A Spatiotemporal Machine Learning Framework for Deer-Vehicle Collision Prediction and Budget-Constrained Intervention Planning",
    outcome: "Accepted at IEEE GHTC 2026",
    year: "2026",
    summary:
      "A spatiotemporal machine learning framework for predicting deer-vehicle collision hotspots and supporting cost-aware intervention planning.",
    points: [
      "Developed prediction and optimization models using Wisconsin crash data from 2018–2025.",
      "Engineered spatial and temporal features capturing seasonal collision risk patterns.",
      "Achieved MAE 0.706 and R² 0.583 with XGBoost while outperforming traditional hotspot approaches.",
    ],
    presentations: ["Presented at WiSys Quick Pitch Competition 2026"],
  },
  {
    id: "r5",
    title:
      "Quantifying Cross-Illumination Domain Shift in YOLO-Based Camera-Trap Wildlife Detection",
    outcome: "Accepted and presented at IEEE EIT 2026",
    year: "2026",
    summary:
      "A computer vision study investigating the impact of illumination changes on wildlife detection performance.",
    points: [
      "Evaluated YOLOv5 and YOLOv8 across daytime RGB and nighttime infrared imagery.",
      "Quantified approximately 0.35 mAP degradation under cross-domain deployment.",
      "Demonstrated improved robustness through mixed-domain training strategies.",
    ],
  },
  {
    id: "r6",
    title:
      "Lightweight Spatiotemporal Machine Learning Framework for Multi-Class Wildlife Roadkill Classification",
    outcome: "Accepted and presented at IEEE EIT 2026",
    year: "2026",
    summary:
      "A lightweight machine learning framework for classifying wildlife road mortality using spatial and temporal predictors.",
    points: [
      "Trained Random Forest and Gradient Boosting models on 5,132 georeferenced wildlife records.",
      "Designed robust validation workflows using stratified train-test splits and cross-validation.",
      "Achieved 89.9% test accuracy with a macro-F1 score of 0.852.",
    ],
  },
  {
    id: "r7",
    title:
      "AI-Powered Animal-Vehicle Collision Prevention Systems: A Comprehensive Review",
    outcome: "Published in Electronics",
    year: "2026",
    doi: "https://doi.org/10.3390/electronics15081767",
    summary:
      "A comprehensive review of AI-powered animal-vehicle collision prevention systems and intelligent sensing technologies.",
    points: [
      "Reviewed computer vision, sensing, and intelligent transportation approaches for wildlife collision prevention.",
      "Evaluated RGB, thermal, LiDAR, and radar-based detection systems.",
      "Proposed a system-level framework integrating sensing, perception, and roadside alert mechanisms.",
    ],
    presentations: ["Presented at the 3-Minute Graduate Project Competition 2025"],
  },
];

const outcomeColor = (outcome: string) => {
  if (outcome.startsWith("Published")) {
    return "from-[var(--moss)] to-[var(--emerald-deep)]";
  }

  if (outcome.startsWith("Accepted")) {
    return "from-[var(--gold)]/40 to-[var(--copper)]/30";
  }

  return "from-foreground/10 to-foreground/5";
};

export function Research() {
  const [active, setActive] = useState<ResearchItem | null>(null);

  return (
    <section id="research" className="relative overflow-hidden px-6 py-32 lg:pl-72">
      <div className="pointer-events-none absolute inset-0 opacity-35">
        <Fireflies count={7} />
      </div>

      <div className="relative z-10 mx-auto max-w-6xl">
        <SectionLabel numeral="IV" label="Research" />

        <h2 className="max-w-2xl font-display text-5xl leading-tight md:text-6xl">
          Leaves of the
          <br />
          <span className="italic text-[var(--gold)]">
            AI knowledge tree.
          </span>
        </h2>

        <p className="mt-5 max-w-2xl text-sm text-muted-foreground">
          Each leaf represents a first-author research contribution in
          healthcare AI, trustworthy AI, computer vision, wildlife analytics,
          and transportation safety. Explore the research journey, outcomes,
          publications, and presentations behind each study.
        </p>

        <div className="mt-14 space-y-4">
          {researchItems.map((item, i) => (
            <motion.button
              key={item.id}
              onClick={() => setActive(item)}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.06 }}
              className="glass group grid w-full grid-cols-[auto_1fr_auto] items-center gap-6 rounded-xl p-5 text-left transition hover:border-[var(--gold)]/40"
            >
              <div
                className={`grid h-12 w-12 place-items-center rounded-lg bg-gradient-to-br ${outcomeColor(
                  item.outcome
                )} ring-1 ring-[var(--gold)]/20`}
              >
                <BookOpen className="h-5 w-5 text-foreground" />
              </div>

              <div>
                <div className="font-display text-lg leading-snug text-foreground">
                  {item.title}
                </div>

                <div className="mt-1 text-xs italic text-muted-foreground">
                  {item.year}
                </div>
              </div>

              <span className="hidden max-w-[220px] rounded-full border border-[var(--gold)]/30 bg-background/40 px-3 py-1 text-right text-[10px] uppercase tracking-[0.16em] text-[var(--gold)] sm:inline">
                {item.outcome}
              </span>
            </motion.button>
          ))}
        </div>
      </div>

      <DetailModal
        open={!!active}
        onClose={() => setActive(null)}
        eyebrow="First-Author Research"
        title={active?.title ?? ""}
      >
        {active && (
          <>
            <div>
              <MetaRow label="Outcome" value={active.outcome} />
              <MetaRow label="Year" value={active.year} />

              {active.presentations?.map((presentation) => (
                <MetaRow
                  key={presentation}
                  label="Presentation"
                  value={presentation}
                />
              ))}

              {active.doi && (
                <MetaRow
                  label="DOI"
                  value={
                    <a
                      href={active.doi}
                      target="_blank"
                      rel="noreferrer noopener"
                      className="inline-flex items-center gap-1 text-[var(--gold)] hover:underline"
                    >
                      {active.doi.replace("https://doi.org/", "")}
                      <ExternalLink className="h-3 w-3" />
                    </a>
                  }
                />
              )}
            </div>

            <Section title="Summary">{active.summary}</Section>

            <Section title="Highlights">
              <ul className="space-y-1.5">
                {active.points.map((point) => (
                  <li key={point} className="flex gap-2">
                    <span className="mt-1.5 inline-block h-1 w-1 rounded-full bg-[var(--gold)]" />
                    {point}
                  </li>
                ))}
              </ul>
            </Section>
          </>
        )}
      </DetailModal>
    </section>
  );
}